### ISSUE TITLE
Create  Database Tables

### ISSUE THREAD

**Issue by JohnMDoll** [nss-day-cohort-60/national-parks-api#2]
The following database tables need to be created:

Users
Parks - ticket #1
Amenities
Park_Amenities
Wildlife
Wildlife_Groups
Park_Wildlife
Natural_Attractions
Park_Natural_Attractions
Campgrounds
Camping_Reservations
Events
Event_Registration
Blogs
Favorite_Types
User_Favorites
Photos
Blog_Photos

**Comment by 24hoax** [comment]
tables exist
