### ISSUE TITLE
FIll Blogs, Photos, Blog_Photos tables (Blog_Photos is join table for Blogs x Photos)

### ISSUE THREAD

**Issue by JohnMDoll** [nss-day-cohort-60/national-parks-api#27]
Need data in Blogs table and Blog_Photos table for client side setup

![Image](https://user-images.githubusercontent.com/101382066/213744693-d052176a-0ed0-43ab-8058-c26f6f6cf82b.png)

![Image](https://user-images.githubusercontent.com/101382066/213744780-759c319a-d397-4b9e-b314-5bcc937ac9a3.png)

**Comment by 24hoax** [comment]
vanessa filled out photos table - i'm doing blogs + blogs_photos
